// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4sfD4q6e97K8JMfXKyzfGHNegas-KVxY',
    appId: '1:900339154147:web:c5c43cf2ab0048509cd9d6',
    messagingSenderId: '900339154147',
    projectId: 'letterboxd-clone-fb2fc',
    authDomain: 'letterboxd-clone-fb2fc.firebaseapp.com',
    storageBucket: 'letterboxd-clone-fb2fc.firebasestorage.app',
    measurementId: 'G-BTDVSZ4J23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALuFW9vLmQLykdqcA11-QJTjWOzFAjqE0',
    appId: '1:900339154147:android:77b2f1392cf2461a9cd9d6',
    messagingSenderId: '900339154147',
    projectId: 'letterboxd-clone-fb2fc',
    storageBucket: 'letterboxd-clone-fb2fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcsxdwsX-UdVm2taGIhVF-HzGGR_vQPUY',
    appId: '1:900339154147:ios:f53582a463f344cc9cd9d6',
    messagingSenderId: '900339154147',
    projectId: 'letterboxd-clone-fb2fc',
    storageBucket: 'letterboxd-clone-fb2fc.firebasestorage.app',
    iosBundleId: 'com.example.letterboxdclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcsxdwsX-UdVm2taGIhVF-HzGGR_vQPUY',
    appId: '1:900339154147:ios:f53582a463f344cc9cd9d6',
    messagingSenderId: '900339154147',
    projectId: 'letterboxd-clone-fb2fc',
    storageBucket: 'letterboxd-clone-fb2fc.firebasestorage.app',
    iosBundleId: 'com.example.letterboxdclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4sfD4q6e97K8JMfXKyzfGHNegas-KVxY',
    appId: '1:900339154147:web:0660386b39661f3a9cd9d6',
    messagingSenderId: '900339154147',
    projectId: 'letterboxd-clone-fb2fc',
    authDomain: 'letterboxd-clone-fb2fc.firebaseapp.com',
    storageBucket: 'letterboxd-clone-fb2fc.firebasestorage.app',
    measurementId: 'G-N7K22YWRVN',
  );
}
